AWSTemplateFormatVersion: 2010-09-09
Description: Similoluwa Okunowo / This Template Creates the EC2 Instance for the Infrastructure Deployment 

Parameters: 
  EnvironmentName: 
    Type: String 
    Description: Environment name for tagging 

  InstanceType: 
    Type: String
    Description: EC2 instance type 
    AllowedValues: 
      - t2.micro 
      - t3.micro 
      - m1.small 
      - m1.large 
    Default: t2.micro 

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Machine Image ID 

  KeyPairName: 
    Type: String 
    Description: Key pair name to be attached to the EC2 Instance 
    Default: theblackdove

Resources: 
  EC2Instance: 
    Type: AWS::EC2::Instance 
    Properties: 
      InstanceType: !Ref InstanceType 
      ImageId: !Ref AmiId 
      KeyName: !Ref KeyPairName 
      SecurityGroups: 
        - Ref: EC2InstanceSecurityGroup
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdk"
        Ebs: 
          VolumeSize: '10'
      Tags: 
        - Key: Name 
          Value: UdacityCiCdInfra
        - Key: Project
          Value: AlxModule4

  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties: 
      GroupDescription: Allow SSH access 
      SecurityGroupIngress: 
        - IpProtocol: tcp 
          FromPort: 22 
          ToPort: 22 
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp 
          FromPOrt: 3000 
          ToPort: 3000 
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name 
          Value: UdacityCiCdInfraSecGrp 
