# Use version 2.1 of the CircleCI pipeline process engine
version: 2.1

# The collection of jobs containing the steps
jobs: 
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - run: echo hello

  print_world:
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - run: echo world

# The workflow section
workflows:
  - print_hello 
  - print_world: 
      requires: 
        - print_hello
