# Use version 2.1 of the CircleCI pipeline process engine
version: 2.1

# The collection of jobs containing the steps
jobs: 
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - run: echo hello

  print_world:
    docker: 
      - image: circleci/node:13.8.0
    steps: 
      - run: echo world

  # Pipeline values 
  print_pipeline_values: 
    docker: 
      - image: circleci/node:latest 
    environment: 
      CIRCLECI_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps: 
      - run: echo "This is the pipeline id - << pipeline.id >>"
      - run: echo $CIRCLECI_COMPARE_URL

  # Using environment variable scopes 
  # Environment variables can be defined by us or bound to a CircleCI scope 
  # Organization-level, Project-level, Pipeline-level, Job-level scopes, Step-level scope
  # CircleCI also provides built-in environment variables
  print_environment_variables_example:
    docker: 
      - image: cimg/base:2020.01
    steps: 
      - run: 
          name: "A simple step to print the environment variable available at the project-level scope."
          command: |
            echo $NAME

# The workflow section
workflows:
  welcome:
    jobs:
      - print_hello 
      - print_world: 
          requires: 
            - print_hello
      - print_pipeline_values
      - print_environment_variables_example
