# Ansible playbook file - create infrastructure exercise
---
- name: CircleCI - Ansible Exercise
  hosts: web 
  user: ubuntu 
  become: true 
  become_method: sudo 
  become_user: root 
  roles:
    - setup_ec2